name: 'Get and Cache Dependencies'
author: mitchell
description: 'Get the dependencies (via npm) and cache them'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      #need to specify which shell for custom composite actions with run key
      shell: bash